### ISSUE TITLE
Unity Projekt und Dokumentation

### ISSUE THREAD

**Issue by NetzwergDE** [cgtuebingen/spatial_xr#11]
- Aufsetzen eines Unity Projektes
(- Erstellen einer Unity Organisation???)
- Dokumentieren, wie man von einem Unity Projekt zur Ansicht in der Brille kommt.

**Comment by kete1goguadze** [comment]
Tasks:
- Wie exportiert man aus Blender?
- Wie gelangt man von Unity zur VR-Brille? 
wichtig: Dokumentation im Wiki (How-to-Guide).

**Comment by fabo-0** [comment]
> * Wie gelangt man von Unity zur VR-Brille?
>   wichtig: Dokumentation im Wiki (How-to-Guide).

Folgender Link beinhaltet viele nützliche Infos, falls jemand noch Fragen dazu hat hilft das vielleicht.

https://www.linkedin.com/pulse/creating-mixed-reality-app-meta-quest-3-using-unity-step-by-step-dev-vumnc
