### ISSUE TITLE
UI Entwurf

### ISSUE THREAD

**Issue by NetzwergDE** [cgtuebingen/spatial_xr#18]
UI-Datei für Unity erstellen. Skripts schreiben und Layout entwerfen über welches man im Programm arbeiten kann.

Was wir wollen ist ein UI mit Schaltflächen (Siehe Bild in Wiki/Anzeige). 

Zusammenarbeit mit Wetter-Gruppe:
- 2d Interface für Menü
- Kalender/Uhrzeit
- Thermometer mit Temperaturanzeige

Optional für den nächsten Sprint:
- (Lupe für Zoom entwerfen)
- (Wetter-Icons anzeigen)

**Comment by NetzwergDE** [comment]
Ist der Issue nicht schon erledigt?

**Comment by fabo-0** [comment]
@NetzwergDE bisher ist nur die Vorbereitung und das Grundgerüst fertig, außerdem hatten wir ja im Meeting noch ein paar Punkte verfeinert die jetzt in diesem Sprint vervollständigt werden sollen.

**Comment by NetzwergDE** [comment]
> @NetzwergDE bisher ist nur die Vorbereitung und das Grundgerüst fertig, außerdem hatten wir ja im Meeting noch ein paar Punkte verfeinert die jetzt in diesem Sprint vervollständigt werden sollen.

Ok, orientiert euch bitte am Zieldefinition Entwurf. Also vorerst mal die größtenteils 2D Anzeigen für Funktion. Aber freue mich schon auf eure Verfeinerungsideen 😃
