### ISSUE TITLE
Zieldefinition für das Endprodukt

### ISSUE THREAD

**Issue by NetzwergDE** [cgtuebingen/spatial_xr#26]
Mit Bildern/3D definieren, wie das 3D Endprodukt auszusehen hat.
Was ist unser Ziel, wie soll das ganze aussehen? Wollen wir das ganze statisch, rollend beweglich, wie soll man Sachen Einstellen, etc.?

**Comment by fabo-0** [comment]
added wiki "Zieldefinition" and readme in code
