### ISSUE TITLE
Wetter Icons

### ISSUE THREAD

**Issue by NetzwergDE** [cgtuebingen/spatial_xr#28]
Icons für den Wetterzustand erstellen/besorgen.

Sowas:
![weather-icon-set-vector-3382960688](https://github.com/cgtuebingen/spatial_xr/assets/148374221/04da5857-b5e8-4408-8d11-2636c46bce2d)

**Comment by fabo-0** [comment]
Can weather Icons from Figma be used? 
For example https://www.figma.com/community/file/1081175425869573366/3d-weather-icons or https://sketchelements.com/3d-weather-icons-pack/
