### ISSUE TITLE
Erstellen des 3D Objektes fürs "MoonU"

### ISSUE THREAD

**Issue by NetzwergDE** [cgtuebingen/spatial_xr#31]
Menüoptionen sollen über das "MoonU" aufrufbar sein.
Dafür bitte eine Mond 3D Objekt erstellen.
Dieser Mond sollte über eine Symbolik verfügen, die eindeutig erkennbar macht, dass durch berühren des Mondes das Menü aufgerufen wird (z.b. Flagge mit Zahnrad drauf).
Der Mond sollte über Texturen verfügen und passend Skaliert sein (Hand auf Mond ruft Menü auf!!!).

Das ganze Objekt bitte einmal im 3D Objekte Ordner speicher und im idealfall in der Unity Szene Einfügen (eigener Branch!).

![grafik](https://github.com/cgtuebingen/spatial_xr/assets/148374221/c5164bae-81f9-45c5-ad5e-f203a25aa3fe)

**Comment by ErencanErdoganTGS** [comment]
Blender Datei vom Mond in 3D-Objekte hochgeladen

**Comment by NetzwergDE** [comment]
Texturen pls 😉
