### ISSUE TITLE
UI mit Basisdaten in Unity

### ISSUE THREAD

**Issue by NetzwergDE** [cgtuebingen/spatial_xr#32]
Es soll ein ein und Ausblendbares UI Fenster erstellt werden, welches die Basisdaten anzeigt.
![grafik](https://github.com/cgtuebingen/spatial_xr/assets/148374221/fb5fd967-6f53-412e-b852-29a34101d1f7)
Dabei sollte der Aktuelle Standort (Default: Internetstandort), die dortige Temperatur, sowie eine Zeitanzeige angezeigt werden.
Ebenfalls soll die Zeitanzeige einstellbar sein, für die Wettervorhersage, in etwa so wie bei Kalender App/ Alarm App, etc.
Dieses UI Fenster soll erstmal nur 2D Dargestellt werden, wenn jemand eine gute 3D Objektgebundene Lösung hat, kann er diese damit umsetzen.

- [x] Stadtname
- [x] Temperatur
- [x] Uhr

**Comment by fabo-0** [comment]
Man könnte für die Uhr/Kalender Einstellung 3d Hexagons anzeigen, so dass das drehen an diesen Intuitiver ist.
Dabei zeigen die Flächen über und unter dem aktuellen Zustand den nächsten/vorherigen leicht ausgegraut an.


![Image](https://github.com/cgtuebingen/spatial_xr/assets/148436213/d94ae8c3-74d8-41ab-b355-c9c48720ea43)
