### ISSUE TITLE
Berührungspunkt auf Globus, beim Antippen

### ISSUE THREAD

**Issue by NetzwergDE** [cgtuebingen/spatial_xr#33]
Koordinaten für den (ungefähren) Berührungspunkt, bei Hand/Controller Kontakt im 3D Raum zugreifbar in einem Interface/Datei festhalten.

User Story 1: (Handtracking)
Ich berühre den Globus mit einem Finger -> 3D Globuskoordinaten, vom ungefähren Ort der Berührt wurde, werden wiederverwendbar, zugreifbar gespeichert.

User Story 2: (Controller)
Ich Klicke mit der Controller Auswahlhilfe (Pointer) auf eine Stelle des Globus (Taste RT [Right Trigger], oder A) -> Koordinaten werden auch hier gespeichert.

**Comment by chrisch12** [comment]
![Screenshot 2024-06-06 132326](https://github.com/cgtuebingen/spatial_xr/assets/148381346/23a127ea-43a3-4f32-bcb8-eb059c6f31ba)
Wir haben den Contactpoint der Kollision mit der Kugel extrahiert. Um die Kollisionen zu testen haben wir die Destroy-Methode benutzt, da man bei Benutzung des VR-Headsets sofort erkennen konnte, dass es zur Kollision kam. Des Weiteren haben wir einen Tag (World) für das Gameobjekt SimpleWorld2 eingeführt, damit man den Namen des Gameobjekts ändern kann, ohne den Code auf den neuen Namen anpassen zu müssen. Um die Kollisionen zu erkennen, mussten wir einen Collider für SimpleWorld2 benutzen. In unserem Fall haben wir einen Mesh-Collider verwendet, der genauer als ein normaler Collider ist (verwendet das tatsächliche Mesh der Kugel als Kollisionshülle) , allerdings einen erhöhten Leistungsaufwand mit sich bringt. Dieses Skript wurde dann nur auf SimpleWorld2 gezogen.
