### ISSUE TITLE
Plazierung und Bewegung des Globuses

### ISSUE THREAD

**Issue by NetzwergDE** [cgtuebingen/spatial_xr#40]
Der Globus soll im Raum akurat Platzierbar sein, hierfür schlage ich folgendes Steuerungsschema vor:

Controler Layout:
![quest-controller-buttons-and-features](https://github.com/cgtuebingen/spatial_xr/assets/148374221/84dccbf2-6241-40c9-b5f5-44217f644b37)

User Story Controler:
Durch Zielen auf die Kugel und drücken des Rechten Grip Buttons, kann der Globus durch Zielen verschoben Werden. Objekt und Wand Kollisionen werden im Idealfall berücksichtigt. Am Boden/ Objektboden wird ein Kreis angezeigt, welcher als Markierung für die Aktuelle Z-Achse dient. Im idealfall wird die Kugel beim Grabben auch hervorgehoben, etwa durch beleuchtete Silhouette, aber dafür gibts einen Extra Issue 😉 #39 

User Story Handtracking:
Ich hebe beide meine Hände und nehme etwa zeitgleich mit der Rechten und Linken Handfläche den Globus in die Hände. Nun kann ich durch paralleles halten der Hände und umpositionieren dieser den Globus im Raum mit mir herum tragen. Durch wegbewegen der Hände von der Kugel lasse ich diese los. Die Kugel hält dann die Position bei, wo sie nach dem Loslassen war. Auch hier wären beim Positionieren Marker schön, aber dafür gibts #39

**Comment by fabo-0** [comment]
Implemented for movement with one hand/controller
