### ISSUE TITLE
Create Movable Object connected to currentWeather in XR Szene

### ISSUE THREAD

**Issue by Mirrorowl** [cgtuebingen/spatial_xr#71]
Create an Object wich later can carry a 3d Object, that shows the weather, in Unity. it should be able to be moved the same way you can interact with the globe. It should be placebale in the air.

- [x] Create empty Object
- [x] test display with random icon
- [x] write and add interaction skript

**Comment by NetzwergDE** [comment]
Moves Connected to Globe
