### ISSUE TITLE
Write WeatherMapGetter and CurrentWeatherMap

### ISSUE THREAD

**Issue by Mirrorowl** [cgtuebingen/spatial_xr#74]
Write a skript to fetch the WeatherMap from OSM, could be implemented same way WeatherGetter is. Connet to @Irgendj0 .
Add CurrentWeatherMap class wich stores it. The default case, when the icon is not toggeld should be the our standart Globe mesh.  Update when Icon is toggeld and then every minute.

**Comment by fabo-0** [comment]
completed in #83
